### ISSUE TITLE
add possibility to override/extend version name and version separator

### ISSUE THREAD

**Issue by skarzi** [reviewdog/action-depup#17]
Hi :wave:

thanks for super GitHub action!

It would be great to have the possibility to replace (or extend) regexp of the separator used to separate version name (e.g `REVIEWDOG_VERSION`) and version (e.g. `0.1.0`) - currently it's equal to `(=|:?\s+)` - which is probably fine for most cases, but, for instance, not when you want to update the value in the file where each line is formatted like `plugin-name:1.2.3`.

It can be done by some action's input e.g. `separator_regexp: ':\s*'`.
Such a configuration option will make `depup` action much more versatile

**Comment by rickstaa** [comment]
@skarzi I think pull request #21 adds this feature.

**Comment by skarzi** [comment]
yes, currently a majority of cases are handled properly!
