### ISSUE TITLE
Transfer repo to the reviewdog organization

### ISSUE THREAD

**Issue by rickstaa** [reviewdog/action-depup#22]
@haya14busa Maybe it is an idea to transfer ownership to the review dog organisation such that multiple members can mantain it. Let me know what you think.

**Comment by haya14busa** [comment]
I sent @skarzi and @rickstaa as collaborators.

I put this repo under my account because I thought it's general actions and not related to reviewdog, but that's a good point.

Looks like it's ok for existing users to move the owner. https://github.community/t/transferring-github-action-to-another-owner/16581

Let me move the repo to the reviewdog org.

**Comment by haya14busa** [comment]
TODOs:  Change the owner name from haya14busa to reviewdog in ...
- [ ] README
- [ ] https://github.com/reviewdog/action-template
- [ ] All existing action-depup users' repos.

As for the third one, it's a bit tedious to change the all repos. 
I wish there was a tool that can edit repos under a certain org (or given repos arguments) in bulk.
Or we can just change them by hand.
Do you have any thought @rickstaa ?

**Comment by rickstaa** [comment]
> I sent @skarzi and @rickstaa as collaborators.
> 
> I put this repo under my account because I thought it's general actions and not related to reviewdog, but that's a good point.
> 
> Looks like it's ok for existing users to move the owner. https://github.community/t/transferring-github-action-to-another-owner/16581
> 
> Let me move the repo to the reviewdog org.

Ah, I see, I was a bit short sighted on that. In the end it doesn't matter under which user/organization the repository is stored. I leave that choose up to you :).

**Comment by rickstaa** [comment]
> TODOs: Change the owner name from haya14busa to reviewdog in ...
> 
>     * [x]  README
> 
>     * [ ]  https://github.com/reviewdog/action-template
> 
>     * [x]  All existing action-depup users' repos.
> 
> 
> As for the third one, it's a bit tedious to change the all repos.
> I wish there was a tool that can edit repos under a certain org (or given repos arguments) in bulk.
> Or we can change them by hand.
> Do you have any thought @rickstaa ?

Actually the third todo isn't an issue. I found out last month that github is smart enough to handle the change using a url redirect :astonished:. To be sure, I performed a new test. You can see [the results here](https://github.com/reviewdog/action-flake8/runs/1545217927?check_suite_focus=true).  You could however include a old url deprication warning annotation but I think the redirect is already sufficient. This way, new users will use the new url and old can use the old one.

**Comment by rickstaa** [comment]
I created a pull request to fix todo 2 might you decide to keep the action under the reviewdog organization. We can also open a vote with the [rest of the team](https://github.com/orgs/reviewdog/teams/reviewdog).

**Comment by haya14busa** [comment]
Thanks!

One remaining concern is about renovate/dependabot support for updating actions' version with old owner.
But, yes, it's true that it's not a big concern as the existing users can use depup as-is.
Let's close the issue and see how it will go.

**Comment by rickstaa** [comment]
@haya14busa I checked the dependabot, and it looks like it can handle the redirect. I also tried to renovate out, and it is also able to parse the right repo information:

![image](https://user-images.githubusercontent.com/17570430/102019729-54511500-3d75-11eb-9327-2aa6c4a79bac.png)

I am, however, unsure if this means that this will also catch a version change. Please don't feel presured to host this in the orginization. Your personal branch is just as good. I'm happy to asist you with maintaining it there. It was just a surgestion I made based on the fact that you use `REVIEWDOG_VERSION` in the readme instead of the general `VERSION` tag. I now see that you can also use this action to update other versions.

**Comment by haya14busa** [comment]
Looks like the dependabot actually uses the commit of the latest release, so I guess it's no problem?
![image](https://user-images.githubusercontent.com/3797062/102079768-9bf89f00-3e50-11eb-9f7b-665a33c4fe86.png)

**Comment by rickstaa** [comment]
@haya14busa Amazing thanks for re-checking. I think we can close this issue for now. I assume since renovate still finds the dependency it also has no issues. I was however not able to find the commit it is currently focuesd on. Neverteless, If there is any issue with renovating we will likely encounter it in the future when the depup action is switched to v2.
